add content to machine api controllers doc
elmiko/ocp-infrastructure-provider-onboarding-guide pull request #18
Opened 2021-11-30 22:33 UTC by elmiko

also creates a new procedure doc for configuring repo integrations and
updates the ccm doc with the new common procedure.

also fixes up the process for red hat reps in the creating an openshift
repository doc.

2021-11-30 22:34 UTC, elmiko commented
@joelspeed @lobziik @alexander-demichev ptal

2021-12-01 16:46 UTC, patrickdillon reviewed
Wow this is really awesome and I learned a lot. I left a few notes/questions.

2021-12-01 16:46 UTC, patrickdillon commented on docs/cloud-controller-manager/index.md
> +[Configuring Basic Repoistory Integrations](../procedures/configuring-repository-integrations)
```suggestion
[Configuring Basic Repository Integrations](../procedures/configuring-repository-integrations)
```

2021-12-01 16:46 UTC, patrickdillon commented on docs/machine-api-controllers/index.md
> +The primary resources of the Machine API are `Machines`, `MachineSets`, and
I often hear the term "machine pool". Does that have a technical definition? Should it be discussed here?

2021-12-01 16:46 UTC, patrickdillon commented on docs/machine-api-controllers/index.md
> +ProviderSpec object should be defined in the same repository as the provider actuator. For example
> ProviderSpec object should be defined in the same repository as the provider actuator.

Is this accurate? The AWS spec is in openshift/api but I assume the actuator is not there? Or am I missing something?

2021-12-01 17:27 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +The primary resources of the Machine API are `Machines`, `MachineSets`, and
so, imo, "machine pool" can be slightly overloaded. we have a use for it internally on openshift, that is not part of machine api, and there is also a CRD in the cluster-api project named MachinePool.

neither one is directly involved with the machine api components though, i don't think it's worth expanding the discussion here.

2021-12-01 17:30 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +ProviderSpec object should be defined in the same repository as the provider actuator. For example
so, this is another tricky part and i've been considering adding a little more text here to help explain.

we have been migrating the api types to openshift/api, in that process we decided to move some of the provider specs over there as well. they could technically live in each provider's repo, but we have been collecting them in the api repo so that we could remove them from the mao repo.

now, for new providers it is perfectly fine to keep the provider spec in the provider repo. we may choose to move it to the openshift/api repo at some point, but it's not a hard requirement. my goal here is to decrease the number of external repos that might need to be touched.

maybe it would be worth explaining some of this reasoning?

2021-12-01 17:37 UTC, elmiko commented
update
* fix spelling error
* fix formatting error with bullet point

2021-12-01 18:06 UTC, JoelSpeed reviewed
This looks great! The feedback is pretty much all nits, hopefully not too many

2021-12-01 18:06 UTC, JoelSpeed commented on docs/machine-api-controllers/index.md
> +itself is simple enough that it can be reproduced here:
Personal preference/ultra nit: The word simple always feels to me like it shouldn't be in docs, take a read through https://jameshfisher.com/2017/02/22/dont-use-simply/ and see if you agree

2021-12-01 18:06 UTC, JoelSpeed commented on docs/machine-api-controllers/index.md
> +### Add Machine API provider repo to OpenShift
Motivation for adding to the openshift org isn't clear to me here, I think there will be questions on why it has to be in the openshift org, we should explain it's not necessary but makes things easier

2021-12-01 18:19 UTC, kwoodson requested changes
@elmiko Thanks for the doc! Few suggestions. Good work.

2021-12-01 18:19 UTC, kwoodson commented on docs/machine-api-controllers/index.md
> +- MachineSet controller - manages MachineSet resources and ensures the presence of the expected number
Might make a comment here that the machineset controller is also in charge of "stamping" out a machine here. This entails unmarshaling the yaml from the machinset's spec.providerspec into a Machine's spec.providerspec.

2021-12-01 18:19 UTC, kwoodson commented on docs/machine-api-controllers/index.md
> +### Add Machine API provider repo to OpenShift
This is a good discussion point. I think we do want to require them under openshift so that we can offer longer term support as well as guarantee the content of the repo. Just a thought.

2021-12-01 18:19 UTC, kwoodson commented on docs/machine-api-controllers/index.md
> +MAO also deploys the validating and mutating webhooks for Machine resources.
This is the only mention of webhooks. I would like a few more sentences of what they do or a link that gives more info.

2021-12-02 11:53 UTC, lobziik commented on docs/machine-api-controllers/index.md
> +the server instances that are configured for inclusion. In a standard
Yeah, +1 for extend this phrase a bit. Perhaps just add short clarification in brackets, like `(virtual machines, bare metal servers)`

2021-12-02 12:19 UTC, lobziik commented on docs/machine-api-controllers/index.md
> +- MachineHealthCheck controller - manages MachineHealthCheck resources. Ensure machines being
I think it might be useful to reference to the docs about MachineHealthCheck here or add MHC short description with docs link around line 30.
https://docs.openshift.com/container-platform/4.9/machine_management/deploying-machine-health-checks.html this one, maybe this doc would fit.

2021-12-02 12:23 UTC, lobziik commented
@elmiko thanks a lot! Few minor suggestions:
- Explain webhooks a bit
- Add some references to further materials about things which was not covered there in details, such as MHCs.

Aside this, looks awesome to me

2021-12-03 13:43 UTC, elmiko commented
thanks for the great feedback folks, i'll work up some changes

2021-12-03 21:50 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +the server instances that are configured for inclusion. In a standard
it seems like we use "machines" in our product docs, i'm not super happy with that terminology but i suppose it makes sense. fwiw, i got the "server instances" stuff from the upstream docs.

2021-12-03 21:50 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +ProviderSpec object should be defined in the same repository as the provider actuator. For example
i broke out that sentence into a new paragraph and added a little more discussion about the reasoning.

2021-12-03 21:52 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +`MachineHealthChecks`. For the purposes of implementing a new infrastructure
i put the code blocks here just to highlight them and designate that these are actual names. i can remove it if you think it's overly confusing.

2021-12-03 21:53 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +Machines represent individual instances within an infrastructure provider that will
or maybe just replace "instances" with "hosts"?

2021-12-03 21:59 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +#### Controllers owned by the Machine API Operator
agreed, i added a paragraph after the list to that effect

2021-12-03 22:00 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +itself is simple enough that it can be reproduced here:
i'm fine to axe it =)

2021-12-03 22:03 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +### Add Machine API provider repo to OpenShift
should we also have the same discussion in the CCM doc? or maybe we should move this discussion to the common procedure doc?

2021-12-03 22:07 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +- MachineSet controller - manages MachineSet resources and ensures the presence of the expected number
i added an extra sentence about creating machines on an increase of replica

2021-12-03 22:44 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +MAO also deploys the validating and mutating webhooks for Machine resources.
i added a new section for webhooks, with a little discussion and a link to the upstream docs

2021-12-03 22:44 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +- MachineHealthCheck controller - manages MachineHealthCheck resources. Ensure machines being
good idea

2021-12-03 22:53 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +### Add Machine API provider repo to OpenShift
i added another paragraph here, happy to take suggestions on the language.

2021-12-03 22:54 UTC, elmiko commented
update
* many small changes to address feedback, i've tried to comment on each place that i changed

2021-12-06 16:14 UTC, lobziik commented
looks great to me :)

2021-12-14 10:15 UTC, JoelSpeed commented on docs/machine-api-controllers/index.md
> +  is therefore responsible for implementing these methods.
This comment isn't resolved, should we include `Exists`?

2021-12-14 10:15 UTC, JoelSpeed commented on docs/machine-api-controllers/index.md
> +to return warnings and errors to the user before a request is made to the Kubernetes API server.
This sentence isn't quite right, the request was made to the API server, otherwise it wouldn't have got to the webhook, perhaps `before the request is accepted by the Kubernetes API server` would be better?

2021-12-14 10:15 UTC, JoelSpeed commented on docs/machine-api-controllers/index.md
> +integration processes have full access to the source repository.
I'm not sure copying is the correct word here. Copying implies that there will be a separate original source, which is what we do for CCMs where we aren't directly involved in the dev. Is moving a better word in this context? We want a single source for the MAPI provider, within the OpenShift org, I think that's what we are trying to say at least

2021-12-14 10:15 UTC, JoelSpeed commented on docs/machine-api-controllers/index.md
> +[Configuring Basic Repoistory Integrations](../procedures/configuring-repository-integrations)
```suggestion
[Configuring Basic Repository Integrations](../procedures/configuring-repository-integrations)
```

2021-12-14 13:46 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +`MachineHealthChecks`. For the purposes of implementing a new infrastructure
sounds good to me

2021-12-14 13:46 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +  is therefore responsible for implementing these methods.
sorry, i missed this one. i can add it. fwiw, i copied this text from our mao docs.

2021-12-14 13:46 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +to return warnings and errors to the user before a request is made to the Kubernetes API server.
+1, i like that

2021-12-14 13:47 UTC, elmiko commented on docs/machine-api-controllers/index.md
> +integration processes have full access to the source repository.
what about "migrating", or perhaps "adding" ?

2021-12-14 14:12 UTC, JoelSpeed commented on docs/machine-api-controllers/index.md
> +integration processes have full access to the source repository.
Migrating would work for me

2021-12-14 19:59 UTC, elmiko commented
updated to address feedback

2021-12-15 10:04 UTC, JoelSpeed approved these changes
LGTM, thanks Mike

2021-12-15 14:42 UTC, kwoodson commented
@elmiko This looks great.  LGTM

2021-12-15 14:50 UTC, merged